### ISSUE TITLE
请问如何开始编译，已经下载成功了

### ISSUE THREAD

**Issue by LxzBUG** [nldzsz/ffmpeg-build-scripts#1]
-e == check build env ! ==
-e check Darwin build env =======
check wget env......
-e check wget ok......
-e check build env success ok! =======

到这里就停止了

**Comment by LxzBUG** [comment]
感谢大佬 已经解决了

**Comment by nldzsz** [comment]
什么问题呢？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 淘二二 <notifications@github.com&gt;
发送时间: 2020年12月24日 21:45
收件人: nldzsz/ffmpeg-build-scripts <ffmpeg-build-scripts@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[nldzsz/ffmpeg-build-scripts] 请问如何开始编译，已经下载成功了 (#1)





 
感谢大佬 已经解决了
