### ISSUE TITLE
./compile-pc.sh mac 报错

### ISSUE THREAD

**Issue by jiangmingz** [nldzsz/ffmpeg-build-scripts#2]
[*] configurate ffmpeg
--------------------
FF_CFG_FLAGS= --enable-small --enable-runtime-cpudetect --disable-debug --disable-all --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-avdevice --enable-avcodec --enable-avformat --enable-avutil --enable-swresample --enable-swscale --enable-avfilter --disable-postproc --disable-avresample --disable-hwaccels --disable-encoders --enable-encoder=mpeg4 --enable-encoder=aac --enable-encoder=ac3 --enable-encoder=mpeg1video --enable-encoder=mp2 --enable-encoder=mjpeg --disable-decoders --enable-decoder=mpeg4 --enable-decoder=aac --enable-decoder=ac3 --enable-decoder=h264 --enable-decoder=mp3float --enable-decoder=mpeg1video --enable-decoder=mp2float --enable-decoder=mjpeg --disable-muxers --enable-muxer=mpegts --enable-muxer=mpeg1system --enable-muxer=flv --enable-muxer=avi --enable-muxer=mp4 --enable-muxer=h264 --enable-muxer=adts --enable-muxer=mp3 --enable-muxer=ac3 --enable-muxer=image2 --enable-muxer=matroska --disable-demuxers --enable-demuxer=mpegts --enable-demuxer=mpegps --enable-demuxer=mpegvideo --enable-demuxer=flv --enable-demuxer=avi --enable-demuxer=mov --enable-demuxer=h264 --enable-demuxer=aac --enable-demuxer=mp3 --enable-demuxer=ac3 --enable-demuxer=image2 --enable-demuxer=matroska --disable-parsers --enable-parser=aac --enable-parser=aac_latm --enable-parser=h264 --enable-parser=mpegvideo --disable-filters --enable-filter=aformat --enable-filter=aresample --enable-filter=volume --enable-filter=scale --enable-filter=transpose --enable-filter=acrossfade --disable-bsfs --enable-bsf=aac_adtstoasc --enable-bsf=h264_mp4toannexb --enable-bsf=extract_extradata --disable-protocols --enable-protocol=file --enable-encoder=h264_videotoolbox --enable-hwaccel=h264_videotoolbox --enable-gpl --enable-libx264 --enable-encoder=libx264 --enable-libmp3lame --enable-encoder=libmp3lame --enable-libfribidi --enable-filter=drawtext --enable-libfreetype --enable-muxer=ass --enable-demuxer=ass --enable-muxer=srt --enable-demuxer=srt --enable-muxer=webvtt --enable-demuxer=webvtt --enable-encoder=ass --enable-decoder=ass --enable-encoder=srt --enable-decoder=srt --enable-encoder=webvtt --enable-decoder=webvtt  --enable-libfontconfig --enable-libass --enable-filter=subtitles  --enable-ffmpeg --enable-ffplay --enable-ffprobe --enable-ffmpeg --enable-ffplay --disable-optimizations --disable-vda
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:94: /libavutil/Makefile: No such file or directory
Makefile:94: /ffbuild/library.mak: No such file or directory
Makefile:96: /fftools/Makefile: No such file or directory
Makefile:97: /doc/Makefile: No such file or directory
Makefile:98: /doc/examples/Makefile: No such file or directory
Makefile:163: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.
Unknown option "--disable-vda".
See ./configure --help for available options.

**Comment by nldzsz** [comment]
windows系统的编译可能会有一些问题，这个后续改进

**Comment by jiangmingz** [comment]
是 mac 系统

**Comment by iter-next** [comment]
/ffmpeg-build-scripts/build/mac-x86_64/x264/lib/lib*.so: No such file or directory
